apiVersion: v1
kind: Service
metadata:
  name: cut-url-frontend
  namespace: cut-url
  labels:
    app: cut-url-frontend
spec:
  type: NodePort
  selector:
    app: cut-url-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30090
      protocol: TCP
